### ISSUE TITLE
Pokemon Go 狩猎ToolsBox - DeSoiat的博客 |(゜-゜)つロ 干杯~-

### ISSUE THREAD

**Issue by DeSoiat** [DeSoiat/web-comment#2]
https://desoiat.github.io/2022/08/26/Pokemon-Go/ 

 hey

**Comment by DeSoiat** [comment]
Testing

**Comment by DeSoiat** [comment]
评论区是直接连接到 库Issue的不用担心我看不到 不过现在在上学 处理bug 这些得很久

**Comment by zlh919730945** [comment]
昨天试了下群里的1.6，还是会有跳到PokemonGo应用设置界面的bug

**Comment by DeSoiat** [comment]
> @zlh919730945
> 昨天试了下群里的1.6，还是会有跳到PokemonGo应用设置界面的bug

已上传新版

**Comment by ahthmz** [comment]
1.17可以重启，1.71重启不了
一加5，安卓7，系统没有后台弹出限制权限设置

**Comment by 512368** [comment]
你好，想问下我按要求设置使用百闪狩猎的过程中，每次狩猎会点击"对战"是什么原因呀？

**Comment by DeSoiat** [comment]
> @512368
> 你好，想问下我按要求设置使用百闪狩猎的过程中，每次狩猎会点击"对战"是什么原因呀？

过程需要

**Comment by DeSoiat** [comment]
> @ahthmz
> 1.17可以重启，1.71重启不了
> 一加5，安卓7，系统没有后台弹出限制权限设置

那就用1.17版本 1.71 关闭重启方式不一样

**Comment by jasajason1992** [comment]
老板 哪里下gps joystick wrapper啊

**Comment by DeSoiat** [comment]
> @jasajason1992
> 老板 哪里下gps joystick wrapper啊

狩猎度盘

**Comment by jasajason1992** [comment]
暗影狩猎点得慢 而且打完火箭队不会自动抓精灵

**Comment by DeSoiat** [comment]
> @jasajason1992
> 暗影狩猎点得慢 而且打完火箭队不会自动抓精灵

只抓百IV暗影宝可梦， 速度提升方面 行程表已满 近期无更新计划

**Comment by zlh919730945** [comment]
1.71好像还是有卡在应用设置界面的bug

**Comment by Pscyubai** [comment]
Version: 9112000
Android: 29

Error: android.app.RemoteServiceException: Bad notification(tag=null, id=7001) posted from package com.startbssl.app.org, crashing app(uid=11405, pid=6832): Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.startbssl.app.org id=0x7f0e0000) visible user=0 )

android.app.RemoteServiceException: Bad notification(tag=null, id=7001) posted from package com.startbssl.app.org, crashing app(uid=11405, pid=6832): Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.startbssl.app.org id=0x7f0e0000) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2540)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by Pscyubai** [comment]
作者大大，这是怎么回事啊

**Comment by PaleNeutron** [comment]
暗影狩猎的传送界面“确定”点不到，确定按键的位置不太一样

**Comment by DeSoiat** [comment]
> @Pscyubai
> 作者大大，这是怎么回事啊

这个bug 是怎么触发的？ 只触发过一次还是固定发生的？

**Comment by DeSoiat** [comment]
> @PaleNeutron
> 暗影狩猎的传送界面“确定”点不到，确定按键的位置不太一样

等更新吧 下个更新会改成坐标点击

**Comment by Pscyubai** [comment]
> @DeSoiat
> > @Pscyubai
> > 作者大大，这是怎么回事啊
> 
> 这个bug 是怎么触发的？ 只触发过一次还是固定发生的？

**Comment by Pscyubai** [comment]
每次固定出现，重装也不行，开始运行就会崩溃，华为P30P

**Comment by Pscyubai** [comment]
> @DeSoiat
> > @Pscyubai
> > 作者大大，这是怎么回事啊
> 
> 这个bug 是怎么触发的？ 只触发过一次还是固定发生的？
每次固定出现，重装也不行，开始运行就会崩溃，华为P30P

**Comment by DeSoiat** [comment]
> @Pscyubai
> > @DeSoiat
> > > @Pscyubai
> > > 作者大大，这是怎么回事啊
> > 
> > 这个bug 是怎么触发的？ 只触发过一次还是固定发生的？
> 每次固定出现，重装也不行，开始运行就会崩溃，华为P30P
> 

鸿蒙系统啊 G 百闪还没适配鸿蒙系统 以我目前的时间和精力还不允许我去做这么大型的适配， 不过从错误报告看来  错误发生在当 百闪激活保活机制的时候 我可以发一份 取消所有的保活机制的版本 但是更多就可能无能为力了 望见谅

**Comment by DeSoiat** [comment]
> @Pscyubai
> > @DeSoiat
> > > @Pscyubai
> > > 作者大大，这是怎么回事啊
> > 
> > 这个bug 是怎么触发的？ 只触发过一次还是固定发生的？
> 每次固定出现，重装也不行，开始运行就会崩溃，华为P30P
> 

无保活版本已上传 onedrive 与 度盘

**Comment by DeSoiat** [comment]
> @PaleNeutron
> 暗影狩猎的传送界面“确定”点不到，确定按键的位置不太一样

1.4 版本已上传

**Comment by chenmiantiao** [comment]
作者大大，部分宝可梦点击不到。例如食梦梦  三蜜蜂这种高悬浮的宝可梦，希望可以修改这个问题

**Comment by DeSoiat** [comment]
> @chenmiantiao
> 作者大大，部分宝可梦点击不到。例如食梦梦  三蜜蜂这种高悬浮的宝可梦，希望可以修改这个问题

你用的1.9版本吗？
